server {
    listen 80;
    server_name stickerloot.live;

    # ACME-challenge для продления сертификата Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Автоматический редирект всех запросов с HTTP на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name stickerloot.live;

    # Пути к твоим новым сертификатам
    ssl_certificate /etc/letsencrypt/live/stickerloot.live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stickerloot.live/privkey.pem;

    # Оптимизация безопасности SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Прокси для API
    location /api {
        proxy_pass http://api:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Прокси для WebSocket
    location /ws {
        proxy_pass http://api:8000/api/v1/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}